### ISSUE TITLE
[Task 8] Redux

### ISSUE THREAD

**Issue by vadym-zinchenko-moc** [MastersAcademy/fe-react-2024#49]
- Main repository - https://github.com/MastersAcademy/fe-react-2024
- Design - https://www.figma.com/file/mRAOMdJiAsD8fHSVnYwUl9/React-web-page
- Branch name - task/08-redux

### Task Description: Implement logic with Redux

The following requirements must be met:

1. **Intall dependencies**:
   - You need to install `redux` and `react-redux`. If you work without Redux Toolkit, you need to install `redux-thunk`. To work with Redux Toolkit, install `@reduxjs/toolkit`.

2. ** Prepare your app to work with Redux**:
   - Need to create `store` and provide it to your `app`.
   
3. ** Move your states and methods to redux**:
   - Need to move your states and methods to redux. Create `reducer` for  `theme` and another one for `products, product details and pagination`.

#### Additional Task (Optional):
- **Showing filtered and full products amount **:
  - Need to implement next logic
    1. On the products page, always display the total number of products, as shown on the screen - `Total amount of products:`
    2. When a filter is applied (e.g., using the search input) and the product count changes, display an additional field - `Filtered amount of products:`
    
    ![Screenshot 2024-06-26 at 16 32 50](https://github.com/MastersAcademy/fe-react-2024/assets/115080771/ffa0e5d9-0816-45c7-955b-3bc113d0ec3b)
  
### Acceptance Criteria for `1`
- [ ] Mentor is added to PR
- [ ] AC copied to PR description
- [ ] Link to deployed version is added to PR
- [ ] Intall dependencies
- [ ] Prepared your app to work with Redux
- [ ] Moved your states and methods to redux

### Acceptance Criteria for `1*`
- [ ] Added a field showing the total number of products
- [ ] Added a field showing the filtered number of products when a filter is applied and amount total and filtered is different
